"""Update download item cascade relationships

Revision ID: 1229c4397b53
Revises: 8b97c50921ee
Create Date: 2025-04-24 21:17:31.082896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1229c4397b53'
down_revision = '8b97c50921ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_items', schema=None) as batch_op:
        batch_op.drop_constraint('download_items_download_set_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('download_items_copied_from_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'download_sets', ['download_set_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'download_items', ['copied_from_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('download_items_copied_from_id_fkey', 'download_items', ['copied_from_id'], ['id'])
        batch_op.create_foreign_key('download_items_download_set_id_fkey', 'download_sets', ['download_set_id'], ['id'])

    # ### end Alembic commands ###
