"""initial migration

Revision ID: 19fe5bd4d51e
Revises: 
Create Date: 2024-10-13 20:33:11.905653

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19fe5bd4d51e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("auth_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("pw_hash", sa.String(length=60), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "worker_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recorded_datetime", sa.TIMESTAMP(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("DEBUG", "INFOLOW", "INFO", "WARNING", "ERROR", name="loglevel"),
            nullable=False,
        ),
        sa.Column("message", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recorded_datetime"),
    )
    op.create_table(
        "download_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "TODO",
                "QUEUED",
                "PROCESSING",
                "COMPLETED",
                "PACKING_FAILED",
                name="downloadsetstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_datetime", sa.TIMESTAMP(), nullable=False),
        sa.Column("queued_datetime", sa.TIMESTAMP(), nullable=True),
        sa.Column("completed_datetime", sa.TIMESTAMP(), nullable=True),
        sa.Column("archive_path", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "download_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "TODO",
                "QUEUED",
                "DOWNLOADING",
                "FINALIZING",
                "COMPLETED",
                "FAILED",
                name="downloaditemstatus",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("audio_only", sa.Boolean(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("added_datetime", sa.TIMESTAMP(), nullable=False),
        sa.Column("download_set_id", sa.String(length=36), nullable=False),
        sa.Column("copied_from_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["copied_from_id"],
            ["download_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["download_set_id"],
            ["download_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("download_items")
    op.drop_table("download_sets")
    op.drop_table("worker_messages")
    op.drop_table("users")
    # ### end Alembic commands ###
