"""Add download_item.artist field

Revision ID: 8b97c50921ee
Revises: c00040348f55
Create Date: 2024-11-10 14:20:56.136929

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b97c50921ee"
down_revision = "c00040348f55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("download_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("artist", sa.String(length=50), nullable=True))
        batch_op.alter_column(
            "title",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=100),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("download_items", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )
        batch_op.drop_column("artist")

    # ### end Alembic commands ###
