_DATE_TIME_DISPLAY_FORMAT = "%m/%d/%Y, %-I:%M:%S %p"

DEFAULT_CONFIG_FILE = "config.dev.yaml"
KEY_ARTIFACTS_DIR = "ARTIFACTS_DIR"
KEY_DEFAULT_WAIT_SECONDS = "DEFAULT_WAIT_SECONDS"
KEY_LOGS_DIR = "LOGS_DIR"

a_dir_log = None
