from App.utils.RuntimeContext import RuntimeContext

DATE_TIME_DISPLAY_FORMAT = "%m/%d/%Y, %-I:%M:%S %p"

KEY_CONFIG_APP_NAME = "APP_NAME"
KEY_CONFIG_DB_ADDRESS = "APP_DB_ADDRESS"
KEY_CONFIG_DB_CATALOG = "APP_DB_CATALOG"
KEY_CONFIG_DB_PASSWORD = "APP_DB_PASSWORD"
KEY_CONFIG_DB_USER = "APP_DB_USER"
KEY_CONFIG_DEBUG_MODE = "APP_DEBUG_MODE"
KEY_CONFIG_DIR_ARTIFACTS = "APP_DIR_ARTIFACTS"
KEY_CONFIG_DIR_LOGS = "APP_DIR_LOGS"
KEY_CONFIG_DOWNLOADER_APP_DIR = "APP_DOWNLOADER_APP_DIR"
KEY_CONFIG_ENVIRONMENT = "APP_ENVIRONMENT"
KEY_CONFIG_WORKER_MIN_IDLE_TIMEOUT_SECONDS = (
    "WORKER_MIN_IDLE_TIMEOUT_SECONDS"
)
KEY_CONFIG_WORKER_MAX_IDLE_TIMEOUT_SECONDS = (
    "WORKER_MAX_IDLE_TIMEOUT_SECONDS"
)

runtime_context = RuntimeContext()
