# common: &common
#   ARTIFACTS_DIR: "{{ ROOT_PATH }}/../../artifacts"

flask:
  name: Video Downloader
  debug: true

app_config:
  # <<: *common
  ENVIRONMENT: development
  SECRET_KEY: develop
  SESSION_PROTECTION: strong
  ARTIFACTS_DIR: "{{ ROOT_PATH }}/../../artifacts"

worker_config:
  # <<: *common
  DEFAULT_WAIT_SECONDS: 30
  ARTIFACTS_DIR: "{{ ROOT_PATH }}/../artifacts"