common: &common
  ARTIFACTS_DIR: "{{ EXE_DIR }}/../artifacts"
  LOGS_DIR: "{{ EXE_DIR }}/../logs"
  SQLALCHEMY_DATABASE_URI: "sqlite:///{{ EXE_DIR }}/../site.db"

flask: &flask
  flask_name: Video Downloader
  flask_debug: true

app_config:
  <<: *flask
  <<: *common
  ENVIRONMENT: development
  SECRET_KEY: develop
  SESSION_PROTECTION: strong

worker_config:
  <<: *common
  DEFAULT_WAIT_SECONDS: 30