common: &common
  flask_name: Video DL
  flask_debug: true
  ARTIFACTS_DIR: "{{ EXE_DIR }}/../artifacts"
  LOGS_DIR: "{{ EXE_DIR }}/../logs"
  SQLALCHEMY_DATABASE_URI: "postgresql://postgres:videodl dev@127.0.0.1:18182/videodl"

app_config:
  <<: *common
  ENVIRONMENT: development
  SECRET_KEY: develop
  SESSION_PROTECTION: strong

worker_config:
  <<: *common
  DEFAULT_WAIT_SECONDS: 30