common: &common
  ARTIFACTS_DIR: "{{ EXE_DIR }}/../artifacts"
  LOGS_DIR: "{{ EXE_DIR }}/../logs"

flask:
  name: Video Downloader
  debug: true

app_config:
  <<: *common
  ENVIRONMENT: development
  SECRET_KEY: develop
  SESSION_PROTECTION: strong

worker_config:
  <<: *common
  DEFAULT_WAIT_SECONDS: 30