
# For testing and prodction, be sure to specifiy --project-name
# when starting docker compose.
# Example: docker-compose --project-name "dev" up --detach

services:
    db:
        image: postgres:16.4
        container_name: ${CONTAINER_NAME}
        restart: unless-stopped
        env_file:
            - ./videodl_postgres.env
        ports:
            - 127.0.0.1:${HOST_PORT}:5432
        volumes:
            - videodl-db-data:/var/lib/postgresql/data

volumes:
    videodl-db-data: