name: Build and Upload Docker Images on Release

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build web Docker image
      run: docker build -t videodl-web -f web.dockerfile .
    
    - name: Build worker Docker image
      run: docker build -t videodl-worker -f worker.dockerfile .
    
    - name: Save web Docker image
      run: docker save videodl-web | gzip > videodl-web.tar.gz
    
    - name: Save worker Docker image
      run: docker save videodl-worker | gzip > videodl-worker.tar.gz
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          videodl-web.tar.gz
          videodl-worker.tar.gz