name: Build and Upload Docker Images on Release

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build web Docker image
      run: docker build -t videodl-web -f web.dockerfile .
    
    - name: Build worker Docker image
      run: docker build -t videodl-worker -f worker.dockerfile .
    
    - name: Save web Docker image
      run: docker save videodl-web | gzip > videodl-web.tar.gz
    
    - name: Save worker Docker image
      run: docker save videodl-worker | gzip > videodl-worker.tar.gz
    
    - name: Upload web image to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./videodl-web.tar.gz
        asset_name: videodl-web.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload worker image to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./videodl-worker.tar.gz
        asset_name: videodl-worker.tar.gz
        asset_content_type: application/gzip