name: CI Deploy

on:
  push:
    branches:
      - 'testing/*'
  release:
    types: [released]

permissions:
  contents: read

env:
  BASE_APP_VERSION: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name}}
  BUILD_TYPE: ${{ github.event_name == 'release' && 'release' || 'testing' }}
  LS_CMD: "ls -lagG --group-directories-first"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Store correct base app version
        if: ${{ env.BUILD_TYPE == 'testing' }}
        run: echo ${{ env.BASE_APP_VERSION }} | awk '{split($0, a, "/"); print "BASE_APP_VERSION="a[2]}' >> $GITHUB_ENV

      - name: Store other build variables
        run: |
          echo "BUILD_DATE=$(TZ="America/New_York" date +"%F %r")" >> $GITHUB_ENV
          echo ${{ github.run_number }} | awk '{printf("%s%04d\n", "BUILD_NUMBER=", $0)}' >> $GITHUB_ENV
          echo ${{ github.sha }} | awk '{printf("%s%s\n", "COMMIT=", substr($0, 1, 10))}' >> $GITHUB_ENV

      # - name: print things
      #   run: |
      #     echo ${BASE_APP_VERSION}
      #     echo ${BUILD_DATE}
      #     echo ${BUILD_NUMBER}
      #     echo ${BUILD_TYPE}
      #     echo ${COMMIT}

      - name: Assemble app version
        run: |
          APP_VERSION="${BASE_APP_VERSION}-${BUILD_NUMBER}"
          if [ "${BUILD_TYPE}" == 'testing' ]; then
              APP_VERSION="${APP_VERSION}.prerelease"
          fi
          APP_VERSION="${APP_VERSION}+${COMMIT}"
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

      # - name: Print true app version
      #   run: echo "${{ env.APP_VERSION }}"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Prune docker files - testing
        if: ${{ env.BUILD_TYPE == 'testing' }}
        run: |
          cd postgres
          ${{ env.LS_CMD }}
          rm --verbose .env-release videodl_postgres.env-release
          mv --verbose .env-testing .env
          mv --verbose videodl_postgres.env-testing videodl_postgres.env
          ${{ env.LS_CMD }}

      - name: Prune docker files - release
        if: ${{ env.BUILD_TYPE == 'release' }}
        run: |
          cd postgres
          ${{ env.LS_CMD }}
          rm --verbose .env-testing videodl_postgres.env-testing
          mv --verbose .env-release .env
          mv --verbose videodl_postgres.env-release videodl_postgres.env
          ${{ env.LS_CMD }}

      - name: Prune systemd files - testing
        if: ${{ env.BUILD_TYPE == 'testing' }}
        run: |
          cd systemd
          ${{ env.LS_CMD }}
          mv --verbose videodl_worker.service videodl_worker-testing.service
          mv --verbose videodl.service videodl-testing.service
          ${{ env.LS_CMD }}

      - name: Prune systemd files - release
        if: ${{ env.BUILD_TYPE == 'release' }}
        run: echo "Nothing to do. This action is just to have a sibling to 'testing'."

      - name: Prune app files
        run: |
          cd src
          ${{ env.LS_CMD }}
          rm --verbose init_db_dev.sh
          rm --verbose seed_db_dev.py
          ${{ env.LS_CMD }}

      - name: Prune app files - testing
        if: ${{ env.BUILD_TYPE == 'testing' }}
        run: |
          cd src
          ${{ env.LS_CMD }}
          rm --verbose .env-release
          mv --verbose .env-testing .env
          ${{ env.LS_CMD }}
