name: CI Deploy

on:
  push:
    branches:
      - 'release/*'
      - 'testing/*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Store version number
        run: |
          echo ${{ github.ref }} | awk '{split($0, a, "/"); print "APP_VERSION="a[4]}' >> $GITHUB_ENV
          echo ${{ github.run_number }} | awk '{printf("%s%04d", "BUILD_NUMBER=", $0)}' >> $GITHUB_ENV
          echo ${{ github.sha}} | awk '{printf("%s%s", "COMMIT=", substr($0, 1, 10))}' >> $GITHUB_ENV

      - name: Store testing branch type indicator
        if: ${{ startsWith(github.ref, 'refs/heads/testing/') }}
        run: echo "BRANCH_TYPE=testing" >> $GITHUB_ENV

      - name: Store release branch type indicator
        if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
        run: echo "BRANCH_TYPE=release" >> $GITHUB_ENV

      - name: print things
        run: |
          echo ${APP_VERSION}
          echo ${BRANCH_TYPE}
          echo ${BUILD_NUMBER}
          echo ${COMMIT}
